/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_STORAGE_FILES           4
#define MMAP_STORAGE_CHECKSUM        0xE583

enum MMAP_STORAGE_LISTS {
    MMAP_STORAGE_ECHO_WAV = 0,        /*!< echo.wav */
    MMAP_STORAGE_JIAO_WO_GAN_MA_WAV = 1,        /*!< jiao_wo_gan_ma.wav */
    MMAP_STORAGE_MUYU_WAV = 2,        /*!< muyu.wav */
    MMAP_STORAGE_WO_QI_LE_WAV = 3,        /*!< wo_qi_le.wav */
};
